backend:
  name: backend-app
  labels:
    app: db
    env: dev
    stack: chatapp
  image:
    repository: glenitashareen/backend
    tag: latest
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_HOST: mysql-service  # Using MYSQL_HOST as in the backend code
    MYSQL_DATABASE: chatdb     # Using MYSQL_DATABASE as in the backend code
    MYSQL_USER: user           # Using MYSQL_USER as in the backend code
    APP_ENV: dev               # Using APP_ENV as in the backend code
  containerPorts:
      backendPort: 4000
  # volume:
  #     name: nginx-proxy-cache-store
  #     mount:
  #         path: /var/lib/mysql
  #         name: nginx-proxy-cache-store
  #     storage: 1T
  #     nfs:
  #         path: /shared_volume
  #         server: dev-cache-filestore.internal.gdev.postmedia.digital
  #     claim:
  #         name: nginx-proxy-cache-store-claim
