frontend:
  name: frontend-app
  labels:
    app: frontend
    env: dev
    stack: chatapp
  image:
    repository: glenitashareen/frontend
    tag: latest
    pullPolicy: Always
  replicas: 3
  configmap:
    ## KEY: "value"
    BACKEND_URL: "http://backend-service.backend.svc.cluster.local:4000"
  containerPorts:
      http: 80
