apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-configmap
  labels:
{{- toYaml .Values.backend.labels | nindent 4 }}
data:
{{- range $k, $v := .Values.backend.configmap }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
